import './globals.css'
import 'lenis/dist/lenis.css'
import { Inter } from 'next/font/google'
import Header from '../components/Header';
import { Analytics } from "@vercel/analytics/next"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Praise | Photographer & Director',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{overflowX: "hidden"}}>
        <Header />
        {children}
        <Analytics />
      </body>
    </html>
  )
}
